User.create(
  first_name: 'Mohamed',
  last_name: 'Nasr',
  business_name: 'PetroHub.org',
  phone_number: '2676073876',
  cell_number: '7329866193',
  street_address: '209 Main st',
  apt_suite: '2nd Floor',
  city: 'Woodbridge',
  state: "New Jersey",
  zip_code: "07095",
  tax_id: "0",
  ssn: "0",
  in_biz: "2",
  email:"sales@petrohub.org",
  password: "2Hard4you!",
  password_confirmation: "2Hard4you!",
  terms: 1,
  role: 4,
  status: 1
  )

  User.create(
    first_name: 'Suyesh',
    last_name: 'Bhandari',
    business_name: 'PetroHub.org',
    phone_number: '2676073876',
    cell_number: '3479016698',
    street_address: '209 Main st',
    apt_suite: '2nd Floor',
    city: 'Woodbridge',
    state: "New Jersey",
    zip_code: "07095",
    tax_id: "1",
    ssn: "1",
    in_biz: "2",
    email:"suyeshb@gmail.com",
    password: "juaN9841%",
    password_confirmation: "juaN9841%",
    terms: 1,
    role: 4,
    status: 1
    )
